# Generated by Django 4.1.5 on 2023-02-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_node_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_node',
            new_name='order_note',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='New', max_length=10),
        ),
    ]
