# Generated by Django 4.1.5 on 2023-02-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_order_node_order_order_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='oderproduct',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('New', 'New'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted')], default='New', max_length=10),
        ),
    ]
