# Generated by Django 4.1.5 on 2023-02-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_varian_category'),
        ('orders', '0005_remove_oderproduct_color_remove_oderproduct_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oderproduct',
            name='variation',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
        migrations.AddField(
            model_name='oderproduct',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
