# Generated by Django 4.1.5 on 2023-02-06 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_alter_variation_varian_category'),
        ('orders', '0006_remove_oderproduct_variation_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderProduct',
            new_name='OrderProduct',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('New', 'New'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted')], default='New', max_length=10),
        ),
    ]
