# Generated by Django 4.1.5 on 2023-02-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status_alter_orderproduct_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('ACCEPTED', 'ACCEPTED'), ('NEW', 'NEW'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=10),
        ),
    ]
