# Generated by Django 4.1.5 on 2023-02-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='oder',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('NEW', 'NEW'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=10),
        ),
    ]
