# Generated by Django 4.1.5 on 2023-02-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_oder_orderproduct_order_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('NEW', 'NEW')], default='NEW', max_length=10),
        ),
    ]
